/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_measurement_kit_jni_sync_OONI */

#ifndef _Included_io_github_measurement_kit_jni_sync_OONI
#define _Included_io_github_measurement_kit_jni_sync_OONI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_measurement_kit_jni_sync_OONI
 * Method:    dnsInjection
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_measurement_1kit_jni_sync_OONI_dnsInjection
  (JNIEnv *, jclass, jstring, jstring, jboolean, jstring);

/*
 * Class:     io_github_measurement_kit_jni_sync_OONI
 * Method:    httpInvalidRequestLine
 * Signature: (Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_measurement_1kit_jni_sync_OONI_httpInvalidRequestLine
  (JNIEnv *, jclass, jstring, jboolean, jstring);

/*
 * Class:     io_github_measurement_kit_jni_sync_OONI
 * Method:    tcpConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_measurement_1kit_jni_sync_OONI_tcpConnect
  (JNIEnv *, jclass, jstring, jstring, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
