/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ooni_mk_MKGeoIPLookupResults */

#ifndef _Included_io_ooni_mk_MKGeoIPLookup
#define _Included_io_ooni_mk_MKGeoIPLookup

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    Good
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_Good
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetBytesSent
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetBytesSent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetBytesRecv
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetBytesRecv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetProbeIP
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetProbeIP
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetProbeASN
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetProbeASN
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetProbeCC
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetProbeCC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetProbeOrg
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetProbeOrg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    GetLogs
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_GetLogs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupResults
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupResults_Delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    New
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_New
  (JNIEnv *, jclass);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    SetTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_SetTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    SetCountryDBPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_SetCountryDBPath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    SetASNDBPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_SetASNDBPath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    SetCABundlePath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_SetCABundlePath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    Perform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_Perform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_ooni_mk_MKGeoIPLookupSettings
 * Method:    Delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_ooni_mk_MKGeoIPLookupSettings_Delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
