#!/bin/sh
set -e

if [ "$ANDROID_HOME" = "" ]; then
  echo "Please, set the ANDROID_HOME environment variable" 1>&2
  exit 1
fi

./gradlew :assembleDebug
cp build/outputs/aar/android-libs-debug.aar $1
gpg -u 738877AA6C829F26A431C5F480B691277733D95B  -b --armor $1
cat template.pom | sed 's/@VERSION@/$(OVERSION)/g' > $2
gpg -u 738877AA6C829F26A431C5F480B691277733D95B -b --armor $2
