#!/bin/sh
set -e

if [ ! -x ./pkgbuild/script/install/install ]; then
  set -x
  git submodule update --init
  set +x
fi

rm -rf MK_DIST/

# x86_64
./pkgbuild/script/install/install testing/android-x86_64-geoip-1.6.12-2
./pkgbuild/script/install/install testing/android-x86_64-libevent-2.1.8-2
./pkgbuild/script/install/install testing/android-x86_64-libressl-2.6.4-2
./pkgbuild/script/install/install testing/android-x86_64-measurement_kit-0.9.0-alpha-3

# TODO(bassosimone): download more archives
