/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class Api {
  public static String getLogLevelErr() {
    return ApiJNI.logLevelErr_get();
  }

  public static String getLogLevelWarning() {
    return ApiJNI.logLevelWarning_get();
  }

  public static String getLogLevelInfo() {
    return ApiJNI.logLevelInfo_get();
  }

  public static String getLogLevelDebug() {
    return ApiJNI.logLevelDebug_get();
  }

  public static String getLogLevelDebug2() {
    return ApiJNI.logLevelDebug2_get();
  }

}
