/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventFailureStartup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventFailureStartup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventFailureStartup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventFailureStartup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFailure(String value) {
    ApiJNI.EventFailureStartup_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return ApiJNI.EventFailureStartup_failure_get(swigCPtr, this);
  }

  public EventFailureStartup() {
    this(ApiJNI.new_EventFailureStartup(), true);
  }

  public final static String key = ApiJNI.EventFailureStartup_key_get();
}
