/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusEnd {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusEnd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusEnd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusEnd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDownloadedKb(double value) {
    ApiJNI.EventStatusEnd_downloadedKb_set(swigCPtr, this, value);
  }

  public double getDownloadedKb() {
    return ApiJNI.EventStatusEnd_downloadedKb_get(swigCPtr, this);
  }

  public void setUploadedKb(double value) {
    ApiJNI.EventStatusEnd_uploadedKb_set(swigCPtr, this, value);
  }

  public double getUploadedKb() {
    return ApiJNI.EventStatusEnd_uploadedKb_get(swigCPtr, this);
  }

  public void setFailure(String value) {
    ApiJNI.EventStatusEnd_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return ApiJNI.EventStatusEnd_failure_get(swigCPtr, this);
  }

  public EventStatusEnd() {
    this(ApiJNI.new_EventStatusEnd(), true);
  }

  public final static String key = ApiJNI.EventStatusEnd_key_get();
}
