/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusGeoipLookup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusGeoipLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusGeoipLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusGeoipLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProbeIp(String value) {
    ApiJNI.EventStatusGeoipLookup_probeIp_set(swigCPtr, this, value);
  }

  public String getProbeIp() {
    return ApiJNI.EventStatusGeoipLookup_probeIp_get(swigCPtr, this);
  }

  public void setProbeAsn(String value) {
    ApiJNI.EventStatusGeoipLookup_probeAsn_set(swigCPtr, this, value);
  }

  public String getProbeAsn() {
    return ApiJNI.EventStatusGeoipLookup_probeAsn_get(swigCPtr, this);
  }

  public void setProbeCc(String value) {
    ApiJNI.EventStatusGeoipLookup_probeCc_set(swigCPtr, this, value);
  }

  public String getProbeCc() {
    return ApiJNI.EventStatusGeoipLookup_probeCc_get(swigCPtr, this);
  }

  public void setProbeNetworkName(String value) {
    ApiJNI.EventStatusGeoipLookup_probeNetworkName_set(swigCPtr, this, value);
  }

  public String getProbeNetworkName() {
    return ApiJNI.EventStatusGeoipLookup_probeNetworkName_get(swigCPtr, this);
  }

  public EventStatusGeoipLookup() {
    this(ApiJNI.new_EventStatusGeoipLookup(), true);
  }

  public final static String key = ApiJNI.EventStatusGeoipLookup_key_get();
}
