/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventMeasurement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventMeasurement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventMeasurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventMeasurement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(long value) {
    ApiJNI.EventMeasurement_idx_set(swigCPtr, this, value);
  }

  public long getIdx() {
    return ApiJNI.EventMeasurement_idx_get(swigCPtr, this);
  }

  public void setJsonStr(String value) {
    ApiJNI.EventMeasurement_jsonStr_set(swigCPtr, this, value);
  }

  public String getJsonStr() {
    return ApiJNI.EventMeasurement_jsonStr_get(swigCPtr, this);
  }

  public EventMeasurement() {
    this(ApiJNI.new_EventMeasurement(), true);
  }

  public final static String key = ApiJNI.EventMeasurement_key_get();
}
