/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventLog {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventLog(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventLog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventLog(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogLevel(String value) {
    ApiJNI.EventLog_logLevel_set(swigCPtr, this, value);
  }

  public String getLogLevel() {
    return ApiJNI.EventLog_logLevel_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    ApiJNI.EventLog_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return ApiJNI.EventLog_message_get(swigCPtr, this);
  }

  public EventLog() {
    this(ApiJNI.new_EventLog(), true);
  }

  public final static String key = ApiJNI.EventLog_key_get();
}
