/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventFailureResolverLookup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventFailureResolverLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventFailureResolverLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventFailureResolverLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFailure(String value) {
    ApiJNI.EventFailureResolverLookup_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return ApiJNI.EventFailureResolverLookup_failure_get(swigCPtr, this);
  }

  public EventFailureResolverLookup() {
    this(ApiJNI.new_EventFailureResolverLookup(), true);
  }

  public final static String key = ApiJNI.EventFailureResolverLookup_key_get();
}
