/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusReportClose {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusReportClose(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusReportClose obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusReportClose(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReportId(String value) {
    ApiJNI.EventStatusReportClose_reportId_set(swigCPtr, this, value);
  }

  public String getReportId() {
    return ApiJNI.EventStatusReportClose_reportId_get(swigCPtr, this);
  }

  public EventStatusReportClose() {
    this(ApiJNI.new_EventStatusReportClose(), true);
  }

  public final static String key = ApiJNI.EventStatusReportClose_key_get();
}
