/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusProgress {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusProgress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusProgress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusProgress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPercentage(double value) {
    ApiJNI.EventStatusProgress_percentage_set(swigCPtr, this, value);
  }

  public double getPercentage() {
    return ApiJNI.EventStatusProgress_percentage_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    ApiJNI.EventStatusProgress_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return ApiJNI.EventStatusProgress_message_get(swigCPtr, this);
  }

  public EventStatusProgress() {
    this(ApiJNI.new_EventStatusProgress(), true);
  }

  public final static String key = ApiJNI.EventStatusProgress_key_get();
}
