/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusUpdateWebsites {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusUpdateWebsites(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusUpdateWebsites obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusUpdateWebsites(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUrl(String value) {
    ApiJNI.EventStatusUpdateWebsites_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return ApiJNI.EventStatusUpdateWebsites_url_get(swigCPtr, this);
  }

  public void setStatus(String value) {
    ApiJNI.EventStatusUpdateWebsites_status_set(swigCPtr, this, value);
  }

  public String getStatus() {
    return ApiJNI.EventStatusUpdateWebsites_status_get(swigCPtr, this);
  }

  public EventStatusUpdateWebsites() {
    this(ApiJNI.new_EventStatusUpdateWebsites(), true);
  }

  public final static String key = ApiJNI.EventStatusUpdateWebsites_key_get();
}
