/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusUpdatePerformance {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusUpdatePerformance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusUpdatePerformance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusUpdatePerformance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDirection(String value) {
    ApiJNI.EventStatusUpdatePerformance_direction_set(swigCPtr, this, value);
  }

  public String getDirection() {
    return ApiJNI.EventStatusUpdatePerformance_direction_get(swigCPtr, this);
  }

  public void setElapsed(double value) {
    ApiJNI.EventStatusUpdatePerformance_elapsed_set(swigCPtr, this, value);
  }

  public double getElapsed() {
    return ApiJNI.EventStatusUpdatePerformance_elapsed_get(swigCPtr, this);
  }

  public void setNumStreams(long value) {
    ApiJNI.EventStatusUpdatePerformance_numStreams_set(swigCPtr, this, value);
  }

  public long getNumStreams() {
    return ApiJNI.EventStatusUpdatePerformance_numStreams_get(swigCPtr, this);
  }

  public void setSpeedKbps(double value) {
    ApiJNI.EventStatusUpdatePerformance_speedKbps_set(swigCPtr, this, value);
  }

  public double getSpeedKbps() {
    return ApiJNI.EventStatusUpdatePerformance_speedKbps_get(swigCPtr, this);
  }

  public EventStatusUpdatePerformance() {
    this(ApiJNI.new_EventStatusUpdatePerformance(), true);
  }

  public final static String key = ApiJNI.EventStatusUpdatePerformance_key_get();
}
