/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusQueued {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusQueued(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusQueued obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusQueued(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EventStatusQueued() {
    this(ApiJNI.new_EventStatusQueued(), true);
  }

  public final static String key = ApiJNI.EventStatusQueued_key_get();
}
