/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class EventStatusResolverLookup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EventStatusResolverLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EventStatusResolverLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_EventStatusResolverLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIpAddress(String value) {
    ApiJNI.EventStatusResolverLookup_ipAddress_set(swigCPtr, this, value);
  }

  public String getIpAddress() {
    return ApiJNI.EventStatusResolverLookup_ipAddress_get(swigCPtr, this);
  }

  public EventStatusResolverLookup() {
    this(ApiJNI.new_EventStatusResolverLookup(), true);
  }

  public final static String key = ApiJNI.EventStatusResolverLookup_key_get();
}
