/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class LogEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_LogEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogLevel(String value) {
    mk_swig_nettestJNI.LogEvent_logLevel_set(swigCPtr, this, value);
  }

  public String getLogLevel() {
    return mk_swig_nettestJNI.LogEvent_logLevel_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    mk_swig_nettestJNI.LogEvent_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return mk_swig_nettestJNI.LogEvent_message_get(swigCPtr, this);
  }

  public LogEvent() {
    this(mk_swig_nettestJNI.new_LogEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.LogEvent_key_get();
}
