/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class MeasurementEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MeasurementEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MeasurementEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_MeasurementEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(long value) {
    mk_swig_nettestJNI.MeasurementEvent_idx_set(swigCPtr, this, value);
  }

  public long getIdx() {
    return mk_swig_nettestJNI.MeasurementEvent_idx_get(swigCPtr, this);
  }

  public void setJsonStr(String value) {
    mk_swig_nettestJNI.MeasurementEvent_jsonStr_set(swigCPtr, this, value);
  }

  public String getJsonStr() {
    return mk_swig_nettestJNI.MeasurementEvent_jsonStr_get(swigCPtr, this);
  }

  public MeasurementEvent() {
    this(mk_swig_nettestJNI.new_MeasurementEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.MeasurementEvent_key_get();
}
