/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestDash extends NettestBasePerformance {
  private transient long swigCPtr;

  protected NettestDash(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestDash_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestDash obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestDash(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestDash_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestDash_change_ownership(this, swigCPtr, true);
  }

  public NettestDash(SettingsDash arg0) {
    this(ApiJNI.new_NettestDash(SettingsDash.getCPtr(arg0), arg0), true);
    ApiJNI.NettestDash_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return (getClass() == NettestDash.class) ? ApiJNI.NettestDash_run(swigCPtr, this) : ApiJNI.NettestDash_runSwigExplicitNettestDash(swigCPtr, this);
  }

}
