/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestBasePerformance extends NettestBase {
  private transient long swigCPtr;

  protected NettestBasePerformance(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestBasePerformance_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestBasePerformance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestBasePerformance(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestBasePerformance_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestBasePerformance_change_ownership(this, swigCPtr, true);
  }

  public void onStatusUpdatePerformance(EventStatusUpdatePerformance arg0) {
    if (getClass() == NettestBasePerformance.class) ApiJNI.NettestBasePerformance_onStatusUpdatePerformance(swigCPtr, this, EventStatusUpdatePerformance.getCPtr(arg0), arg0); else ApiJNI.NettestBasePerformance_onStatusUpdatePerformanceSwigExplicitNettestBasePerformance(swigCPtr, this, EventStatusUpdatePerformance.getCPtr(arg0), arg0);
  }

  public NettestBasePerformance() {
    this(ApiJNI.new_NettestBasePerformance(), true);
    ApiJNI.NettestBasePerformance_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
