/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class Nettest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Nettest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Nettest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_Nettest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    mk_swig_nettestJNI.Nettest_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    mk_swig_nettestJNI.Nettest_change_ownership(this, swigCPtr, true);
  }

  public Nettest(Settings arg0) {
    this(mk_swig_nettestJNI.new_Nettest(Settings.getCPtr(arg0), arg0), true);
    mk_swig_nettestJNI.Nettest_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return mk_swig_nettestJNI.Nettest_run(swigCPtr, this);
  }

  public void interrupt() {
    mk_swig_nettestJNI.Nettest_interrupt(swigCPtr, this);
  }

  public void onFailureAsnLookup(FailureAsnLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureAsnLookup(swigCPtr, this, FailureAsnLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureAsnLookupSwigExplicitNettest(swigCPtr, this, FailureAsnLookupEvent.getCPtr(arg0), arg0);
  }

  public void onFailureCcLookup(FailureCcLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureCcLookup(swigCPtr, this, FailureCcLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureCcLookupSwigExplicitNettest(swigCPtr, this, FailureCcLookupEvent.getCPtr(arg0), arg0);
  }

  public void onFailureIpLookup(FailureIpLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureIpLookup(swigCPtr, this, FailureIpLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureIpLookupSwigExplicitNettest(swigCPtr, this, FailureIpLookupEvent.getCPtr(arg0), arg0);
  }

  public void onFailureMeasurement(FailureMeasurementEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureMeasurement(swigCPtr, this, FailureMeasurementEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureMeasurementSwigExplicitNettest(swigCPtr, this, FailureMeasurementEvent.getCPtr(arg0), arg0);
  }

  public void onFailureMeasurementSubmission(FailureMeasurementSubmissionEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureMeasurementSubmission(swigCPtr, this, FailureMeasurementSubmissionEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureMeasurementSubmissionSwigExplicitNettest(swigCPtr, this, FailureMeasurementSubmissionEvent.getCPtr(arg0), arg0);
  }

  public void onFailureReportCreate(FailureReportCreateEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureReportCreate(swigCPtr, this, FailureReportCreateEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureReportCreateSwigExplicitNettest(swigCPtr, this, FailureReportCreateEvent.getCPtr(arg0), arg0);
  }

  public void onFailureReportClose(FailureReportCloseEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureReportClose(swigCPtr, this, FailureReportCloseEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureReportCloseSwigExplicitNettest(swigCPtr, this, FailureReportCloseEvent.getCPtr(arg0), arg0);
  }

  public void onFailureResolverLookup(FailureResolverLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureResolverLookup(swigCPtr, this, FailureResolverLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureResolverLookupSwigExplicitNettest(swigCPtr, this, FailureResolverLookupEvent.getCPtr(arg0), arg0);
  }

  public void onFailureStartup(FailureStartupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onFailureStartup(swigCPtr, this, FailureStartupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onFailureStartupSwigExplicitNettest(swigCPtr, this, FailureStartupEvent.getCPtr(arg0), arg0);
  }

  public void onLog(LogEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onLog(swigCPtr, this, LogEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onLogSwigExplicitNettest(swigCPtr, this, LogEvent.getCPtr(arg0), arg0);
  }

  public void onMeasurement(MeasurementEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onMeasurement(swigCPtr, this, MeasurementEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onMeasurementSwigExplicitNettest(swigCPtr, this, MeasurementEvent.getCPtr(arg0), arg0);
  }

  public void onStatusEnd(StatusEndEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusEnd(swigCPtr, this, StatusEndEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusEndSwigExplicitNettest(swigCPtr, this, StatusEndEvent.getCPtr(arg0), arg0);
  }

  public void onStatusGeoipLookup(StatusGeoipLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusGeoipLookup(swigCPtr, this, StatusGeoipLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusGeoipLookupSwigExplicitNettest(swigCPtr, this, StatusGeoipLookupEvent.getCPtr(arg0), arg0);
  }

  public void onStatusProgress(StatusProgressEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusProgress(swigCPtr, this, StatusProgressEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusProgressSwigExplicitNettest(swigCPtr, this, StatusProgressEvent.getCPtr(arg0), arg0);
  }

  public void onStatusQueued(StatusQueuedEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusQueued(swigCPtr, this, StatusQueuedEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusQueuedSwigExplicitNettest(swigCPtr, this, StatusQueuedEvent.getCPtr(arg0), arg0);
  }

  public void onStatusMeasurementStart(StatusMeasurementStartEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusMeasurementStart(swigCPtr, this, StatusMeasurementStartEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusMeasurementStartSwigExplicitNettest(swigCPtr, this, StatusMeasurementStartEvent.getCPtr(arg0), arg0);
  }

  public void onStatusMeasurementSubmission(StatusMeasurementSubmissionEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusMeasurementSubmission(swigCPtr, this, StatusMeasurementSubmissionEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusMeasurementSubmissionSwigExplicitNettest(swigCPtr, this, StatusMeasurementSubmissionEvent.getCPtr(arg0), arg0);
  }

  public void onStatusMeasurementDone(StatusMeasurementDoneEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusMeasurementDone(swigCPtr, this, StatusMeasurementDoneEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusMeasurementDoneSwigExplicitNettest(swigCPtr, this, StatusMeasurementDoneEvent.getCPtr(arg0), arg0);
  }

  public void onStatusReportClose(StatusReportCloseEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusReportClose(swigCPtr, this, StatusReportCloseEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusReportCloseSwigExplicitNettest(swigCPtr, this, StatusReportCloseEvent.getCPtr(arg0), arg0);
  }

  public void onStatusReportCreate(StatusReportCreateEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusReportCreate(swigCPtr, this, StatusReportCreateEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusReportCreateSwigExplicitNettest(swigCPtr, this, StatusReportCreateEvent.getCPtr(arg0), arg0);
  }

  public void onStatusResolverLookup(StatusResolverLookupEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusResolverLookup(swigCPtr, this, StatusResolverLookupEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusResolverLookupSwigExplicitNettest(swigCPtr, this, StatusResolverLookupEvent.getCPtr(arg0), arg0);
  }

  public void onStatusStarted(StatusStartedEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusStarted(swigCPtr, this, StatusStartedEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusStartedSwigExplicitNettest(swigCPtr, this, StatusStartedEvent.getCPtr(arg0), arg0);
  }

  public void onStatusUpdatePerformance(StatusUpdatePerformanceEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusUpdatePerformance(swigCPtr, this, StatusUpdatePerformanceEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusUpdatePerformanceSwigExplicitNettest(swigCPtr, this, StatusUpdatePerformanceEvent.getCPtr(arg0), arg0);
  }

  public void onStatusUpdateWebsites(StatusUpdateWebsitesEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onStatusUpdateWebsites(swigCPtr, this, StatusUpdateWebsitesEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onStatusUpdateWebsitesSwigExplicitNettest(swigCPtr, this, StatusUpdateWebsitesEvent.getCPtr(arg0), arg0);
  }

  public void onTaskTerminated(TaskTerminatedEvent arg0) {
    if (getClass() == Nettest.class) mk_swig_nettestJNI.Nettest_onTaskTerminated(swigCPtr, this, TaskTerminatedEvent.getCPtr(arg0), arg0); else mk_swig_nettestJNI.Nettest_onTaskTerminatedSwigExplicitNettest(swigCPtr, this, TaskTerminatedEvent.getCPtr(arg0), arg0);
  }

}
