/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestHttpInvalidRequestLine extends NettestBase {
  private transient long swigCPtr;

  protected NettestHttpInvalidRequestLine(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestHttpInvalidRequestLine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestHttpInvalidRequestLine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestHttpInvalidRequestLine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestHttpInvalidRequestLine_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestHttpInvalidRequestLine_change_ownership(this, swigCPtr, true);
  }

  public NettestHttpInvalidRequestLine(SettingsHttpInvalidRequestLine arg0) {
    this(ApiJNI.new_NettestHttpInvalidRequestLine(SettingsHttpInvalidRequestLine.getCPtr(arg0), arg0), true);
    ApiJNI.NettestHttpInvalidRequestLine_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return (getClass() == NettestHttpInvalidRequestLine.class) ? ApiJNI.NettestHttpInvalidRequestLine_run(swigCPtr, this) : ApiJNI.NettestHttpInvalidRequestLine_runSwigExplicitNettestHttpInvalidRequestLine(swigCPtr, this);
  }

}
