/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestWebConnectivity extends NettestBaseWebsites {
  private transient long swigCPtr;

  protected NettestWebConnectivity(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestWebConnectivity_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestWebConnectivity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestWebConnectivity(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestWebConnectivity_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestWebConnectivity_change_ownership(this, swigCPtr, true);
  }

  public NettestWebConnectivity(SettingsWebConnectivity arg0) {
    this(ApiJNI.new_NettestWebConnectivity(SettingsWebConnectivity.getCPtr(arg0), arg0), true);
    ApiJNI.NettestWebConnectivity_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return (getClass() == NettestWebConnectivity.class) ? ApiJNI.NettestWebConnectivity_run(swigCPtr, this) : ApiJNI.NettestWebConnectivity_runSwigExplicitNettestWebConnectivity(swigCPtr, this);
  }

}
