/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestBaseWebsites extends NettestBase {
  private transient long swigCPtr;

  protected NettestBaseWebsites(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestBaseWebsites_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestBaseWebsites obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestBaseWebsites(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestBaseWebsites_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestBaseWebsites_change_ownership(this, swigCPtr, true);
  }

  public void onStatusUpdateWebsites(EventStatusUpdateWebsites arg0) {
    if (getClass() == NettestBaseWebsites.class) ApiJNI.NettestBaseWebsites_onStatusUpdateWebsites(swigCPtr, this, EventStatusUpdateWebsites.getCPtr(arg0), arg0); else ApiJNI.NettestBaseWebsites_onStatusUpdateWebsitesSwigExplicitNettestBaseWebsites(swigCPtr, this, EventStatusUpdateWebsites.getCPtr(arg0), arg0);
  }

  public NettestBaseWebsites() {
    this(ApiJNI.new_NettestBaseWebsites(), true);
    ApiJNI.NettestBaseWebsites_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
