/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestMultiNdt extends NettestBasePerformance {
  private transient long swigCPtr;

  protected NettestMultiNdt(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestMultiNdt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestMultiNdt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestMultiNdt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestMultiNdt_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestMultiNdt_change_ownership(this, swigCPtr, true);
  }

  public NettestMultiNdt(SettingsMultiNdt arg0) {
    this(ApiJNI.new_NettestMultiNdt(SettingsMultiNdt.getCPtr(arg0), arg0), true);
    ApiJNI.NettestMultiNdt_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return (getClass() == NettestMultiNdt.class) ? ApiJNI.NettestMultiNdt_run(swigCPtr, this) : ApiJNI.NettestMultiNdt_runSwigExplicitNettestMultiNdt(swigCPtr, this);
  }

}
