/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class NettestFacebookMessenger extends NettestBase {
  private transient long swigCPtr;

  protected NettestFacebookMessenger(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.NettestFacebookMessenger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NettestFacebookMessenger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_NettestFacebookMessenger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ApiJNI.NettestFacebookMessenger_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ApiJNI.NettestFacebookMessenger_change_ownership(this, swigCPtr, true);
  }

  public NettestFacebookMessenger(SettingsFacebookMessenger arg0) {
    this(ApiJNI.new_NettestFacebookMessenger(SettingsFacebookMessenger.getCPtr(arg0), arg0), true);
    ApiJNI.NettestFacebookMessenger_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean run() {
    return (getClass() == NettestFacebookMessenger.class) ? ApiJNI.NettestFacebookMessenger_run(swigCPtr, this) : ApiJNI.NettestFacebookMessenger_runSwigExplicitNettestFacebookMessenger(swigCPtr, this);
  }

}
