/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class Settings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Settings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Settings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_Settings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    mk_swig_nettestJNI.Settings_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    mk_swig_nettestJNI.Settings_change_ownership(this, swigCPtr, true);
  }

  public void setLogFilepath(String value) {
    mk_swig_nettestJNI.Settings_logFilepath_set(swigCPtr, this, value);
  }

  public String getLogFilepath() {
    return mk_swig_nettestJNI.Settings_logFilepath_get(swigCPtr, this);
  }

  public void setLogLevel(String value) {
    mk_swig_nettestJNI.Settings_logLevel_set(swigCPtr, this, value);
  }

  public String getLogLevel() {
    return mk_swig_nettestJNI.Settings_logLevel_get(swigCPtr, this);
  }

  public void setOutputFilepath(String value) {
    mk_swig_nettestJNI.Settings_outputFilepath_set(swigCPtr, this, value);
  }

  public String getOutputFilepath() {
    return mk_swig_nettestJNI.Settings_outputFilepath_get(swigCPtr, this);
  }

  public void setBouncerBaseUrl(String value) {
    mk_swig_nettestJNI.Settings_bouncerBaseUrl_set(swigCPtr, this, value);
  }

  public String getBouncerBaseUrl() {
    return mk_swig_nettestJNI.Settings_bouncerBaseUrl_get(swigCPtr, this);
  }

  public void setCollectorBaseUrl(String value) {
    mk_swig_nettestJNI.Settings_collectorBaseUrl_set(swigCPtr, this, value);
  }

  public String getCollectorBaseUrl() {
    return mk_swig_nettestJNI.Settings_collectorBaseUrl_get(swigCPtr, this);
  }

  public void setDnsNameserver(String value) {
    mk_swig_nettestJNI.Settings_dnsNameserver_set(swigCPtr, this, value);
  }

  public String getDnsNameserver() {
    return mk_swig_nettestJNI.Settings_dnsNameserver_get(swigCPtr, this);
  }

  public void setDnsEngine(String value) {
    mk_swig_nettestJNI.Settings_dnsEngine_set(swigCPtr, this, value);
  }

  public String getDnsEngine() {
    return mk_swig_nettestJNI.Settings_dnsEngine_get(swigCPtr, this);
  }

  public void setGeoipAsnPath(String value) {
    mk_swig_nettestJNI.Settings_geoipAsnPath_set(swigCPtr, this, value);
  }

  public String getGeoipAsnPath() {
    return mk_swig_nettestJNI.Settings_geoipAsnPath_get(swigCPtr, this);
  }

  public void setGeoipCountryPath(String value) {
    mk_swig_nettestJNI.Settings_geoipCountryPath_set(swigCPtr, this, value);
  }

  public String getGeoipCountryPath() {
    return mk_swig_nettestJNI.Settings_geoipCountryPath_get(swigCPtr, this);
  }

  public void setIgnoreBouncerError(boolean value) {
    mk_swig_nettestJNI.Settings_ignoreBouncerError_set(swigCPtr, this, value);
  }

  public boolean getIgnoreBouncerError() {
    return mk_swig_nettestJNI.Settings_ignoreBouncerError_get(swigCPtr, this);
  }

  public void setIgnoreOpenReportError(boolean value) {
    mk_swig_nettestJNI.Settings_ignoreOpenReportError_set(swigCPtr, this, value);
  }

  public boolean getIgnoreOpenReportError() {
    return mk_swig_nettestJNI.Settings_ignoreOpenReportError_get(swigCPtr, this);
  }

  public void setMaxRuntime(double value) {
    mk_swig_nettestJNI.Settings_maxRuntime_set(swigCPtr, this, value);
  }

  public double getMaxRuntime() {
    return mk_swig_nettestJNI.Settings_maxRuntime_get(swigCPtr, this);
  }

  public void setNetCaBundlePath(String value) {
    mk_swig_nettestJNI.Settings_netCaBundlePath_set(swigCPtr, this, value);
  }

  public String getNetCaBundlePath() {
    return mk_swig_nettestJNI.Settings_netCaBundlePath_get(swigCPtr, this);
  }

  public void setNetTimeout(double value) {
    mk_swig_nettestJNI.Settings_netTimeout_set(swigCPtr, this, value);
  }

  public double getNetTimeout() {
    return mk_swig_nettestJNI.Settings_netTimeout_get(swigCPtr, this);
  }

  public void setNoBouncer(boolean value) {
    mk_swig_nettestJNI.Settings_noBouncer_set(swigCPtr, this, value);
  }

  public boolean getNoBouncer() {
    return mk_swig_nettestJNI.Settings_noBouncer_get(swigCPtr, this);
  }

  public void setNoCollector(boolean value) {
    mk_swig_nettestJNI.Settings_noCollector_set(swigCPtr, this, value);
  }

  public boolean getNoCollector() {
    return mk_swig_nettestJNI.Settings_noCollector_get(swigCPtr, this);
  }

  public void setNoAsnLookup(boolean value) {
    mk_swig_nettestJNI.Settings_noAsnLookup_set(swigCPtr, this, value);
  }

  public boolean getNoAsnLookup() {
    return mk_swig_nettestJNI.Settings_noAsnLookup_get(swigCPtr, this);
  }

  public void setNoCcLookup(boolean value) {
    mk_swig_nettestJNI.Settings_noCcLookup_set(swigCPtr, this, value);
  }

  public boolean getNoCcLookup() {
    return mk_swig_nettestJNI.Settings_noCcLookup_get(swigCPtr, this);
  }

  public void setNoIpLookup(boolean value) {
    mk_swig_nettestJNI.Settings_noIpLookup_set(swigCPtr, this, value);
  }

  public boolean getNoIpLookup() {
    return mk_swig_nettestJNI.Settings_noIpLookup_get(swigCPtr, this);
  }

  public void setNoFileReport(boolean value) {
    mk_swig_nettestJNI.Settings_noFileReport_set(swigCPtr, this, value);
  }

  public boolean getNoFileReport() {
    return mk_swig_nettestJNI.Settings_noFileReport_get(swigCPtr, this);
  }

  public void setNoResolverLookup(boolean value) {
    mk_swig_nettestJNI.Settings_noResolverLookup_set(swigCPtr, this, value);
  }

  public boolean getNoResolverLookup() {
    return mk_swig_nettestJNI.Settings_noResolverLookup_get(swigCPtr, this);
  }

  public void setProbeAsn(String value) {
    mk_swig_nettestJNI.Settings_probeAsn_set(swigCPtr, this, value);
  }

  public String getProbeAsn() {
    return mk_swig_nettestJNI.Settings_probeAsn_get(swigCPtr, this);
  }

  public void setProbeCc(String value) {
    mk_swig_nettestJNI.Settings_probeCc_set(swigCPtr, this, value);
  }

  public String getProbeCc() {
    return mk_swig_nettestJNI.Settings_probeCc_get(swigCPtr, this);
  }

  public void setProbeIp(String value) {
    mk_swig_nettestJNI.Settings_probeIp_set(swigCPtr, this, value);
  }

  public String getProbeIp() {
    return mk_swig_nettestJNI.Settings_probeIp_get(swigCPtr, this);
  }

  public void setRandomizeInput(boolean value) {
    mk_swig_nettestJNI.Settings_randomizeInput_set(swigCPtr, this, value);
  }

  public boolean getRandomizeInput() {
    return mk_swig_nettestJNI.Settings_randomizeInput_get(swigCPtr, this);
  }

  public void setSaveRealProbeAsn(boolean value) {
    mk_swig_nettestJNI.Settings_saveRealProbeAsn_set(swigCPtr, this, value);
  }

  public boolean getSaveRealProbeAsn() {
    return mk_swig_nettestJNI.Settings_saveRealProbeAsn_get(swigCPtr, this);
  }

  public void setSaveRealProbeCc(boolean value) {
    mk_swig_nettestJNI.Settings_saveRealProbeCc_set(swigCPtr, this, value);
  }

  public boolean getSaveRealProbeCc() {
    return mk_swig_nettestJNI.Settings_saveRealProbeCc_get(swigCPtr, this);
  }

  public void setSaveRealProbeIp(boolean value) {
    mk_swig_nettestJNI.Settings_saveRealProbeIp_set(swigCPtr, this, value);
  }

  public boolean getSaveRealProbeIp() {
    return mk_swig_nettestJNI.Settings_saveRealProbeIp_get(swigCPtr, this);
  }

  public void setSaveRealResolverIp(boolean value) {
    mk_swig_nettestJNI.Settings_saveRealResolverIp_set(swigCPtr, this, value);
  }

  public boolean getSaveRealResolverIp() {
    return mk_swig_nettestJNI.Settings_saveRealResolverIp_get(swigCPtr, this);
  }

  public void setSoftwareName(String value) {
    mk_swig_nettestJNI.Settings_softwareName_set(swigCPtr, this, value);
  }

  public String getSoftwareName() {
    return mk_swig_nettestJNI.Settings_softwareName_get(swigCPtr, this);
  }

  public void setSoftwareVersion(String value) {
    mk_swig_nettestJNI.Settings_softwareVersion_set(swigCPtr, this, value);
  }

  public String getSoftwareVersion() {
    return mk_swig_nettestJNI.Settings_softwareVersion_get(swigCPtr, this);
  }

  public void addAnnotation(String key, String value) {
    mk_swig_nettestJNI.Settings_addAnnotation(swigCPtr, this, key, value);
  }

  public void addInput(String value) {
    mk_swig_nettestJNI.Settings_addInput(swigCPtr, this, value);
  }

  public void addInputFilepath(String value) {
    mk_swig_nettestJNI.Settings_addInputFilepath(swigCPtr, this, value);
  }

  public Settings() {
    this(mk_swig_nettestJNI.new_Settings(), true);
    mk_swig_nettestJNI.Settings_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
