/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class SettingsMultiNdt extends SettingsBase {
  private transient long swigCPtr;

  protected SettingsMultiNdt(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.SettingsMultiNdt_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SettingsMultiNdt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_SettingsMultiNdt(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SettingsMultiNdt() {
    this(ApiJNI.new_SettingsMultiNdt(), true);
  }

  public final static String name = ApiJNI.SettingsMultiNdt_name_get();
}
