/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class SettingsWhatsapp extends SettingsBase {
  private transient long swigCPtr;

  protected SettingsWhatsapp(long cPtr, boolean cMemoryOwn) {
    super(ApiJNI.SettingsWhatsapp_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SettingsWhatsapp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ApiJNI.delete_SettingsWhatsapp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setAllEndpoints(boolean value) {
    ApiJNI.SettingsWhatsapp_allEndpoints_set(swigCPtr, this, value);
  }

  public boolean getAllEndpoints() {
    return ApiJNI.SettingsWhatsapp_allEndpoints_get(swigCPtr, this);
  }

  public SettingsWhatsapp() {
    this(ApiJNI.new_SettingsWhatsapp(), true);
  }

  public final static String name = ApiJNI.SettingsWhatsapp_name_get();
}
