/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusReportCloseEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusReportCloseEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusReportCloseEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusReportCloseEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReportId(String value) {
    mk_swig_nettestJNI.StatusReportCloseEvent_reportId_set(swigCPtr, this, value);
  }

  public String getReportId() {
    return mk_swig_nettestJNI.StatusReportCloseEvent_reportId_get(swigCPtr, this);
  }

  public StatusReportCloseEvent() {
    this(mk_swig_nettestJNI.new_StatusReportCloseEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusReportCloseEvent_key_get();
}
