/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusResolverLookupEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusResolverLookupEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusResolverLookupEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusResolverLookupEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIpAddress(String value) {
    mk_swig_nettestJNI.StatusResolverLookupEvent_ipAddress_set(swigCPtr, this, value);
  }

  public String getIpAddress() {
    return mk_swig_nettestJNI.StatusResolverLookupEvent_ipAddress_get(swigCPtr, this);
  }

  public StatusResolverLookupEvent() {
    this(mk_swig_nettestJNI.new_StatusResolverLookupEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusResolverLookupEvent_key_get();
}
