/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusStartedEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusStartedEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusStartedEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusStartedEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StatusStartedEvent() {
    this(mk_swig_nettestJNI.new_StatusStartedEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusStartedEvent_key_get();
}
