/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusEndEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusEndEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusEndEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusEndEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDownloadedKb(double value) {
    mk_swig_nettestJNI.StatusEndEvent_downloadedKb_set(swigCPtr, this, value);
  }

  public double getDownloadedKb() {
    return mk_swig_nettestJNI.StatusEndEvent_downloadedKb_get(swigCPtr, this);
  }

  public void setUploadedKb(double value) {
    mk_swig_nettestJNI.StatusEndEvent_uploadedKb_set(swigCPtr, this, value);
  }

  public double getUploadedKb() {
    return mk_swig_nettestJNI.StatusEndEvent_uploadedKb_get(swigCPtr, this);
  }

  public void setFailure(String value) {
    mk_swig_nettestJNI.StatusEndEvent_failure_set(swigCPtr, this, value);
  }

  public String getFailure() {
    return mk_swig_nettestJNI.StatusEndEvent_failure_get(swigCPtr, this);
  }

  public StatusEndEvent() {
    this(mk_swig_nettestJNI.new_StatusEndEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusEndEvent_key_get();
}
