/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusUpdateWebsitesEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusUpdateWebsitesEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusUpdateWebsitesEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusUpdateWebsitesEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUrl(String value) {
    mk_swig_nettestJNI.StatusUpdateWebsitesEvent_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return mk_swig_nettestJNI.StatusUpdateWebsitesEvent_url_get(swigCPtr, this);
  }

  public void setStatus(String value) {
    mk_swig_nettestJNI.StatusUpdateWebsitesEvent_status_set(swigCPtr, this, value);
  }

  public String getStatus() {
    return mk_swig_nettestJNI.StatusUpdateWebsitesEvent_status_get(swigCPtr, this);
  }

  public StatusUpdateWebsitesEvent() {
    this(mk_swig_nettestJNI.new_StatusUpdateWebsitesEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusUpdateWebsitesEvent_key_get();
}
