/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ooni.mk.nettest.swig;

public class StatusMeasurementStartEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StatusMeasurementStartEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StatusMeasurementStartEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mk_swig_nettestJNI.delete_StatusMeasurementStartEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(long value) {
    mk_swig_nettestJNI.StatusMeasurementStartEvent_idx_set(swigCPtr, this, value);
  }

  public long getIdx() {
    return mk_swig_nettestJNI.StatusMeasurementStartEvent_idx_get(swigCPtr, this);
  }

  public void setInput(String value) {
    mk_swig_nettestJNI.StatusMeasurementStartEvent_input_set(swigCPtr, this, value);
  }

  public String getInput() {
    return mk_swig_nettestJNI.StatusMeasurementStartEvent_input_get(swigCPtr, this);
  }

  public StatusMeasurementStartEvent() {
    this(mk_swig_nettestJNI.new_StatusMeasurementStartEvent(), true);
  }

  public final static String key = mk_swig_nettestJNI.StatusMeasurementStartEvent_key_get();
}
