/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <string>


#include <stdint.h>		// Use the C99 official header



#include "ooni.hpp"



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_new_1OrchestrateAuth(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OrchestrateAuth *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (OrchestrateAuth *)new OrchestrateAuth();
  *(OrchestrateAuth **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1auth_1token(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (arg1)->auth_token();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1set_1auth_1token(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_auth_token(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1expiry_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (arg1)->expiry_time();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1set_1expiry_1time(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_expiry_time(arg2);
}


SWIGEXPORT jboolean JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1logged_1in(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (bool)(arg1)->logged_in();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1set_1logged_1in(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->set_logged_in(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1username(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (arg1)->username();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1set_1username(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_username(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1password(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (arg1)->password();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1set_1password(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_password(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1make_1password(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  result = OrchestrateAuth::make_password();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1load(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jobject jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  mk_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->load(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1loads(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jobject jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  mk_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->loads(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1dump(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jobject jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string arg2 ;
  mk_error_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return 0;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return 0;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  result = (arg1)->dump(arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1dumps(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (arg1)->dumps();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateAuth_1is_1valid(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  result = (bool)(arg1)->is_valid();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_delete_1OrchestrateAuth(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OrchestrateAuth *arg1 = (OrchestrateAuth *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OrchestrateAuth **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_new_1OrchestrateClient(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  OrchestrateClient *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (OrchestrateClient *)new OrchestrateClient();
  *(OrchestrateClient **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1verbosity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  uint32_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  (arg1)->set_verbosity(arg2);
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1increase_1verbosity(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  (arg1)->increase_verbosity();
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1use_1logcat(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  (arg1)->use_logcat();
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1logfile(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_logfile(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1available_1bandwidth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->available_bandwidth();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1available_1bandwidth(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_available_bandwidth(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1device_1token(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->device_token();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1device_1token(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_device_token(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1events_1url(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->events_url();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1events_1url(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_events_url(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1language(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->language();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1language(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_language(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1network_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->network_type();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1network_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_network_type(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1geoip_1country_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->geoip_country_path();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1geoip_1country_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_geoip_country_path(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1geoip_1asn_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->geoip_asn_path();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1geoip_1asn_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_geoip_asn_path(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1platform(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->platform();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1platform(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_platform(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1probe_1asn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->probe_asn();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1probe_1asn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_probe_asn(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1probe_1cc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->probe_cc();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1probe_1cc(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_probe_cc(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1probe_1family(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->probe_family();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1probe_1family(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_probe_family(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1registry_1url(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->registry_url();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1registry_1url(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_registry_url(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1software_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->software_name();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1software_1name(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_software_name(arg2);
}


SWIGEXPORT jstring JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1software_1version(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->software_version();
  jresult = jenv->NewStringUTF((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1software_1version(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  (arg1)->set_software_version(arg2);
}


SWIGEXPORT jobject JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1supported_1tests(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  mk_array_list_strings_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  result = (arg1)->supported_tests();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1set_1supported_1tests(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  mk_list_strings_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  arg2 = jarg2; 
  (arg1)->set_supported_tests(arg2);
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1register_1probe(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobject jarg3) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  std::string arg2 ;
  mk_orchestrate_register_probe_callback_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  } 
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  (&arg2)->assign(arg2_pstr);
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  arg3 = jarg3; 
  (arg1)->register_probe(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1find_1location(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  mk_orchestrate_find_location_callback_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  arg2 = jarg2; 
  (arg1)->find_location(arg2);
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_OrchestrateClient_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jobject jarg3) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  OrchestrateAuth arg2 ;
  mk_orchestrate_update_callback_t arg3 ;
  OrchestrateAuth *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(OrchestrateClient **)&jarg1; 
  argp2 = *(OrchestrateAuth **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null OrchestrateAuth");
    return ;
  }
  arg2 = *argp2; 
  arg3 = jarg3; 
  (arg1)->update(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_openobservatory_measurement_1kit_swig_mk_1swig_1ooniJNI_delete_1OrchestrateClient(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  OrchestrateClient *arg1 = (OrchestrateClient *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(OrchestrateClient **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

