#!/bin/sh
set -e
ROOTDIR=$(cd $(dirname $0)/../ && pwd -P)
cd $ROOTDIR

package=src/main/java/org/openobservatory/measurement_kit/nettests

for t in                                                                       \
  DashTest                                                                     \
  DnsInjectionTest                                                             \
  FacebookMessengerTest                                                        \
  HttpHeaderFieldManipulationTest                                              \
  HttpInvalidRequestLineTest                                                   \
  MeekFrontedRequestsTest                                                      \
  MultiNdtTest                                                                 \
  NdtTest                                                                      \
  TcpConnectTest                                                               \
  TelegramTest                                                                 \
  WebConnectivityTest                                                          \
  WhatsappTest
do
  set -x
  m4 -D MK_TEST_NAME=$t $package/BaseTest.m4 > $package/$t.java
  set +x
done

set -x
m4 jni/wrappers/nettests.m4 | clang-format > jni/wrappers/nettests.hpp
