#!/bin/sh
set -e
ROOTDIR=$(cd $(dirname $(dirname $0)) && pwd -P)
cd $ROOTDIR

JAVA_HEADERS="/Library/Java/Home/include"

# For now, I guess I'm the only one with this :^)
MK_HOME="/usr/local/Cellar/measurement-kit/HEAD"

CXX=clang++
CPPFLAGS="-I $JAVA_HEADERS -I $JAVA_HEADERS/darwin -I $MK_HOME/include"
CXXFLAGS="-Wall -Wextra -fPIC -std=c++14"
LDFLAGS="-shared -L $MK_HOME/lib"
LIBS="-lmeasurement_kit"
TARGET="libmeasurement_kit_java.dylib"

for file in `ls jni/wrappers/*.cpp`; do
    object=`echo $file | sed 's/\.cpp$/.o/g'`
    echo "* g++ $CPPFLAGS $CXXFLAGS -c $file -o $object"
    $CXX $CPPFLAGS $CXXFLAGS -c $file -o $object
done

$CXX `ls jni/wrappers/*.o` $LDFLAGS $LIBS -o $TARGET
