#!/bin/sh
set -e
ROOTDIR=$(cd $(dirname $0)/../ && pwd -P)
cd $ROOTDIR
package=src/main/java/io/ooni/mk/nettest/swig
rm -rf $package
# Note: the arch doesn't matter: nettest.hpp is machine independent
swig -IMK_DIST/android/measurement-kit/0.9.0-alpha.6-1/armeabi-v7a/include/    \
     -c++ -package io.ooni.mk.nettest.swig -java jni/wrappers/nettest.i
install -d $package
for file in jni/wrappers/*.java; do
  mv $file $package
done
for file in jni/wrappers/*.cxx; do
  mv $file `echo $file | sed 's/\.cxx$/.cpp/g'`
done
