#!/bin/sh
set -e

if [ "$ANDROID_HOME" = "" ]; then
  echo "Please, set the ANDROID_HOME environment variable" 1>&2
  exit 1
fi

./gradlew :assembleDebug
cp build/outputs/aar/android-libs-debug.aar $1
cat template.pom | sed "s/@VERSION@/$3/g" > $2
