#!/bin/sh -e
baseurl="https://github.com/measurement-kit/script-build-android/releases/"
v="0.9.3-1"
tarball="measurement-kit-android-$v.tar.gz"
sha256="550e037bf89aa4943ac31badf6ad42cc7bba4741950e7b269dac5f92ad3a7726"
o=MK_DIST
set -x
curl -fsSLO $baseurl/download/v$v/$tarball
[ "$sha256" = "`shasum -a 256 $tarball | awk '{print $1}'`" ]
rm -rf $o
install -d $o
(
 set -x
 cd $o
 tar -xzf ../$tarball
)
