#!/bin/sh -e
baseurl="https://github.com/measurement-kit/script-build-android/releases/"
v="0.9.2-5-debug-crash"
tarball="measurement-kit-android-$v.tar.gz"
sha256="7f1408a932643a6134a31f97bc6e1197c63ca72fcab92c594a6c6cce30544cfd"
o=MK_DIST
set -x
curl -fsSLO $baseurl/download/v$v/$tarball
[ "$sha256" = "`shasum -a 256 $tarball | awk '{print $1}'`" ]
rm -rf $o
install -d $o
(
 set -x
 cd $o
 tar -xzf ../$tarball
)
