#!/bin/sh -e
baseurl="https://github.com/measurement-kit/script-build-android/releases/"
v="0.9.2-2"
tarball="measurement-kit-android-$v.tar.gz"
sha256="febadd69ac972fca3c34d451d5fbabcdffac059305b13dd8382858c855c00eda"
o=MK_DIST
set -x
curl -fsSLO $baseurl/download/v$v/$tarball
[ "$sha256" = "`shasum -a 256 $tarball | awk '{print $1}'`" ]
rm -rf $o
install -d $o
(
 set -x
 cd $o
 tar -xzf ../$tarball
)
