#!/bin/sh

set -e
ROOTDIR=$(cd $(dirname $(dirname $0)) && pwd -P)
cd $ROOTDIR

echo "java -Djava.library.path=`pwd` -cp src/main/java:example/java \"$1\""
java -Djava.library.path=`pwd` -cp src/main/java:example/java "$1"
