#!/bin/sh
set -e
ROOTDIR=$(cd $(dirname $(dirname $0)) && pwd -P)
cd $ROOTDIR

JAVA_HEADERS="/usr/lib/jvm/java-9-openjdk-amd64/include"

CXX=g++
CPPFLAGS="-I $JAVA_HEADERS -I $JAVA_HEADERS/linux"
CXXFLAGS="-Wall -Wextra -fPIC"
LDFLAGS="-shared"
LIBS="-lmeasurement_kit"
TARGET="libmeasurement_kit_java.so"

for file in `ls jni/wrappers/*.cpp`; do
    object=`echo $file | sed 's/\.cpp$/.o/g'`
    echo "* g++ $CPPFLAGS $CXXFLAGS -c $file -o $object"
    $CXX $CPPFLAGS $CXXFLAGS -c $file -o $object
done

$CXX `ls jni/wrappers/*.o` $LDFLAGS $LIBS -o $TARGET
