#!/bin/sh
set -e
for file in `find mkall-java/src/main/java -type f -name \*.java`; do
  echo "* Copy mkall-java's `basename $file` in src/main/java/io/ooni/mk"
  install -m644 $file src/main/java/io/ooni/mk
done
for file in `find mkall-java/src/mkall -type f -name \*.cpp -o -name \*.h`; do
  echo "* Copy mkall-java's `basename $file` in jni"
  install -m644 $file jni
done
